name: reeds_tautomers
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit
  - matplotlib
  - pandas
  - notebook
  - numpy
  - scipy
  - scikit-learn
  - nb_conda_kernels
  - ipykernel
  - pymbar
  - pip:
    - d3blocks
